In [1]:
print("Hello I am startung my learning journey")

Hello I am startung my learning journey


In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


# scaler

In [9]:
scalar=torch.tensor(7)
print(scalar)

tensor(7)


In [8]:
# get number back as python int
scalar.item()

7

In [11]:
scalar.ndim

0

In [27]:
# vector
vector=torch.tensor([[7,6,5],[8,8,8]])
vector


tensor([[7, 6, 5],
        [8, 8, 8]])

In [23]:
vector.ndim

2

In [25]:
vector.shape

torch.Size([2, 3])

In [28]:
vector[0][1]

tensor(6)

In [29]:
# TENSOR
TENSOR=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

In [30]:
TENSOR

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [32]:
TENSOR.ndim

2

In [33]:
TENSOR.shape

torch.Size([3, 3])

In [35]:
# TENSOR
TENSOR=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [37]:
TENSOR.ndim

3

In [38]:
TENSOR.shape

torch.Size([1, 3, 3])

In [48]:
# create rendom tensors

random_tensor=torch.rand(3,4)
random_tensor


tensor([[0.9625, 0.7438, 0.8680, 0.3256],
        [0.7146, 0.5288, 0.6830, 0.0387],
        [0.3361, 0.8728, 0.1357, 0.5617]])

In [51]:

# create a rendome temsor with similar shape to an image

random_image_size_tensor=torch.rand(size=(224,224,3)) # height,width,color channels (RGB)
random_image_size_tensor

tensor([[[0.9998, 0.4626, 0.6171],
         [0.2543, 0.8864, 0.6059],
         [0.0385, 0.8301, 0.5044],
         ...,
         [0.4724, 0.6572, 0.4030],
         [0.7021, 0.1140, 0.4729],
         [0.1414, 0.6180, 0.5610]],

        [[0.3491, 0.1950, 0.0012],
         [0.4239, 0.3060, 0.6514],
         [0.5683, 0.7754, 0.0559],
         ...,
         [0.2849, 0.4583, 0.5421],
         [0.3452, 0.7673, 0.2458],
         [0.0204, 0.8164, 0.2515]],

        [[0.9838, 0.3889, 0.0750],
         [0.3658, 0.0194, 0.3961],
         [0.7592, 0.0595, 0.8313],
         ...,
         [0.2164, 0.1894, 0.8283],
         [0.7542, 0.9363, 0.2252],
         [0.7102, 0.6173, 0.4659]],

        ...,

        [[0.1367, 0.7279, 0.6797],
         [0.3884, 0.3566, 0.2456],
         [0.3069, 0.6066, 0.9147],
         ...,
         [0.4456, 0.1231, 0.0752],
         [0.6596, 0.3915, 0.1066],
         [0.8342, 0.9389, 0.5442]],

        [[0.4210, 0.0439, 0.2329],
         [0.6287, 0.5477, 0.0050],
         [0.

In [53]:
# create tensor of zeros and ones

zero=torch.zeros(2,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [56]:
zero1=torch.zeros_like(zero)
zero1

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [58]:
# create tensors of ones

ones=torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [59]:
ones.dtype

torch.float32

In [64]:
# createing a range of numbers

tensor_range=torch.arange(1,10)
tensor_range

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
tensor_range1=torch.arange(start=1,end=10,step=2)
tensor_range1


tensor([1, 3, 5, 7, 9])

In [69]:
# creating tensors like

tensor_zero=torch.zeros_like(input=tensor_range)
tensor_zero

tensor([0, 0, 0, 0, 0])

# Tensor Datatypes

In [81]:
float_32_tensor=torch.tensor([1.0,2.1,3.0],
                             dtype=None,
                             device=None,
                             requires_grad=False)
float_32_tensor,float_32_tensor.dtype

(tensor([1.0000, 2.1000, 3.0000]), torch.float32)

In [83]:
float_16_tensor1=torch.tensor([5.0,1.1,9.0],
                              dtype=torch.float16)
float_16_tensor1,float_16_tensor1.dtype

(tensor([5.0000, 1.0996, 9.0000], dtype=torch.float16), torch.float16)

In [88]:
tensor2=float_32_tensor*float_16_tensor1
tensor2.dtype

torch.float32

# reshaping,view, stacking (vstack,hstack),permute, squeezing and unsqueezin tensors



In [19]:
# create a tensor

import torch
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [20]:
# add an extra dimension
x_reshaped=x.reshape(1,9)
x_reshaped,x_reshaped.ndim,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), 2, torch.Size([1, 9]))

In [21]:
# add an extra dimension
x_reshaped1=x.reshape(9,1)
x_reshaped1,x_reshaped1.ndim,x_reshaped1.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 2,
 torch.Size([9, 1]))

In [18]:
# add an extra dimension
x_reshaped=x.reshape(5,2)
x_reshaped,x_reshaped.ndim,x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 2,
 torch.Size([5, 2]))

In [25]:
# change the view
z=x.view(1,9)
z,z.shape

# changes z changes x (becouse view of a tensor shares the same mamory as the original input)


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [28]:
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [30]:
# stack tensors on top of each other
x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [31]:
x_stacked=torch.stack([x,x,x,x],dim=1)
x_stacked


tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [32]:
# squeez and unsqueez

x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [33]:
x_reshaped.shape,x_reshaped.ndim

(torch.Size([1, 9]), 2)

In [39]:
x_squeezed=x_reshaped.squeeze()
x_squeezed,x_reshaped

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [40]:
x_reshaped.ndim,x_reshaped.shape

(2, torch.Size([1, 9]))

In [41]:
x_squeezed.ndim,x_squeezed.shape

(1, torch.Size([9]))

In [51]:
x=torch.rand(3,5,4)
x

tensor([[[0.2376, 0.0831, 0.9794, 0.2655],
         [0.1202, 0.1726, 0.3567, 0.1549],
         [0.2097, 0.2329, 0.0127, 0.0881],
         [0.2282, 0.9522, 0.7889, 0.0236],
         [0.9260, 0.6543, 0.4792, 0.2164]],

        [[0.8695, 0.1711, 0.5925, 0.1874],
         [0.5599, 0.6569, 0.6591, 0.2067],
         [0.9983, 0.0690, 0.0479, 0.5855],
         [0.7309, 0.2232, 0.8958, 0.8801],
         [0.0445, 0.7941, 0.2105, 0.8806]],

        [[0.7032, 0.2336, 0.1171, 0.0372],
         [0.5031, 0.3039, 0.1434, 0.4569],
         [0.5319, 0.2433, 0.0070, 0.8220],
         [0.0549, 0.3694, 0.5713, 0.6489],
         [0.5057, 0.2496, 0.2058, 0.2120]]])

In [52]:
x.shape,x.ndim

(torch.Size([3, 5, 4]), 3)

In [67]:
unsqueez_x=x.unsqueeze(0)
unsqueez_x,unsqueez_x.shape,unsqueez_x.ndim

(tensor([[[[0.2376, 0.0831, 0.9794, 0.2655],
           [0.1202, 0.1726, 0.3567, 0.1549],
           [0.2097, 0.2329, 0.0127, 0.0881],
           [0.2282, 0.9522, 0.7889, 0.0236],
           [0.9260, 0.6543, 0.4792, 0.2164]],
 
          [[0.8695, 0.1711, 0.5925, 0.1874],
           [0.5599, 0.6569, 0.6591, 0.2067],
           [0.9983, 0.0690, 0.0479, 0.5855],
           [0.7309, 0.2232, 0.8958, 0.8801],
           [0.0445, 0.7941, 0.2105, 0.8806]],
 
          [[0.7032, 0.2336, 0.1171, 0.0372],
           [0.5031, 0.3039, 0.1434, 0.4569],
           [0.5319, 0.2433, 0.0070, 0.8220],
           [0.0549, 0.3694, 0.5713, 0.6489],
           [0.5057, 0.2496, 0.2058, 0.2120]]]]),
 torch.Size([1, 3, 5, 4]),
 4)

In [69]:
# torch.permute() - rearrange the dimensions of a target tensor in a specific order
unsqueez_x,unsqueez_x.shape,unsqueez_x.ndim

(tensor([[[[0.2376, 0.0831, 0.9794, 0.2655],
           [0.1202, 0.1726, 0.3567, 0.1549],
           [0.2097, 0.2329, 0.0127, 0.0881],
           [0.2282, 0.9522, 0.7889, 0.0236],
           [0.9260, 0.6543, 0.4792, 0.2164]],
 
          [[0.8695, 0.1711, 0.5925, 0.1874],
           [0.5599, 0.6569, 0.6591, 0.2067],
           [0.9983, 0.0690, 0.0479, 0.5855],
           [0.7309, 0.2232, 0.8958, 0.8801],
           [0.0445, 0.7941, 0.2105, 0.8806]],
 
          [[0.7032, 0.2336, 0.1171, 0.0372],
           [0.5031, 0.3039, 0.1434, 0.4569],
           [0.5319, 0.2433, 0.0070, 0.8220],
           [0.0549, 0.3694, 0.5713, 0.6489],
           [0.5057, 0.2496, 0.2058, 0.2120]]]]),
 torch.Size([1, 3, 5, 4]),
 4)

In [73]:
permuted_x=unsqueez_x.permute(1,3,0,2)
permuted_x,permuted_x.shape

(tensor([[[[0.2376, 0.1202, 0.2097, 0.2282, 0.9260]],
 
          [[0.0831, 0.1726, 0.2329, 0.9522, 0.6543]],
 
          [[0.9794, 0.3567, 0.0127, 0.7889, 0.4792]],
 
          [[0.2655, 0.1549, 0.0881, 0.0236, 0.2164]]],
 
 
         [[[0.8695, 0.5599, 0.9983, 0.7309, 0.0445]],
 
          [[0.1711, 0.6569, 0.0690, 0.2232, 0.7941]],
 
          [[0.5925, 0.6591, 0.0479, 0.8958, 0.2105]],
 
          [[0.1874, 0.2067, 0.5855, 0.8801, 0.8806]]],
 
 
         [[[0.7032, 0.5031, 0.5319, 0.0549, 0.5057]],
 
          [[0.2336, 0.3039, 0.2433, 0.3694, 0.2496]],
 
          [[0.1171, 0.1434, 0.0070, 0.5713, 0.2058]],
 
          [[0.0372, 0.4569, 0.8220, 0.6489, 0.2120]]]]),
 torch.Size([3, 4, 1, 5]))

# numpy array to tensor

In [74]:
import torch
import numpy as np

array=np.arange(1.0,8.0)
array

array([1., 2., 3., 4., 5., 6., 7.])

In [99]:
tensor=torch.from_numpy(array)
tensor


tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [103]:

tensor=torch.from_numpy(array).type(torch.float32)
tensor,tensor.dtype


(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.float32)

# Reproducbility (trying to take random out of random)

In [118]:
tensor_a=torch.rand(3,4)
tensor_b=torch.rand(3,4)

print(tensor_a)
print(tensor_b)
print(tensor_a==tensor_b)


tensor([[0.6347, 0.1815, 0.2485, 0.0550],
        [0.1924, 0.5991, 0.1450, 0.7227],
        [0.2092, 0.3436, 0.7537, 0.7189]])
tensor([[0.6256, 0.7624, 0.6867, 0.9559],
        [0.2592, 0.3710, 0.5479, 0.5480],
        [0.7909, 0.0353, 0.2338, 0.7389]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [146]:
# let's make some random but reproducible tensors
import torch

# set the rendom seed

RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
random_tensor_c=torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_d=torch.rand(3,4)
# torch.manual_seed(RANDOM_SEED)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c==random_tensor_d)




tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
